server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# 数据库连接配置
database:
  logger:
    path: "logs/sql"
    level: "all"
    stdout: true
    ctxKeys: [ "RequestId" ]

  default: # todo  修改成自己的密码
    link: "mariadb:bluebell:454FrEp2AYBdmJNG@tcp(43.139.17.97:3306)/bluebell"
    debug: true


# Redis 配置示例
redis:
  default:
    address: 43.139.17.97:13654
    db: 1
    pass: 45928ddacQWE
    idleTimeout: 600