// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Community is the golang structure of table community for DAO operations like Where/Data.
type Community struct {
	g.Meta        `orm:"table:community, do:true"`
	Id            interface{} //
	CommunityId   interface{} //
	CommunityName interface{} //
	Introduction  interface{} // 简介
	CreateTime    *gtime.Time //
	UpdateTime    *gtime.Time //
}
