// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Post is the golang structure of table post for DAO operations like Where/Data.
type Post struct {
	g.Meta      `orm:"table:post, do:true"`
	Id          interface{} //
	Title       interface{} //
	PostId      interface{} // 帖子id
	Content     interface{} // 内容
	CommunityId interface{} // 所属社区
	AuthorId    interface{} // 作者用户id
	CreateTime  *gtime.Time //
	UpdateTime  *gtime.Time //
}
