// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CommunityDao is the data access object for table community.
type CommunityDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns CommunityColumns // columns contains all the column names of Table for convenient usage.
}

// CommunityColumns defines and stores column names for table community.
type CommunityColumns struct {
	Id            string //
	CommunityId   string //
	CommunityName string //
	Introduction  string // 简介
	CreateTime    string //
	UpdateTime    string //
}

// communityColumns holds the columns for table community.
var communityColumns = CommunityColumns{
	Id:            "id",
	CommunityId:   "community_id",
	CommunityName: "community_name",
	Introduction:  "introduction",
	CreateTime:    "create_time",
	UpdateTime:    "update_time",
}

// NewCommunityDao creates and returns a new DAO object for table data access.
func NewCommunityDao() *CommunityDao {
	return &CommunityDao{
		group:   "default",
		table:   "community",
		columns: communityColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CommunityDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CommunityDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CommunityDao) Columns() CommunityColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CommunityDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CommunityDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CommunityDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
