// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goframe-bluebell/internal/dao/internal"
)

// internalCommunityDao is internal type for wrapping internal DAO implements.
type internalCommunityDao = *internal.CommunityDao

// communityDao is the data access object for table community.
// You can define custom methods on it to extend its functionality as you wish.
type communityDao struct {
	internalCommunityDao
}

var (
	// Community is globally public accessible object for table community operations.
	Community = communityDao{
		internal.NewCommunityDao(),
	}
)

// Fill with you ideas below.
