// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Community is the golang structure for table community.
type Community struct {
	Id            int         `json:"id"            description:""`
	CommunityId   uint        `json:"communityId"   description:""`
	CommunityName string      `json:"communityName" description:""`
	Introduction  string      `json:"introduction"  description:"简介"`
	CreateTime    *gtime.Time `json:"createTime"    description:""`
	UpdateTime    *gtime.Time `json:"updateTime"    description:""`
}
