// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Post is the golang structure for table post.
type Post struct {
	Id          int64       `json:"id"          description:""`
	Title       string      `json:"title"       description:""`
	PostId      int64       `json:"postId"      description:"帖子id"`
	Content     string      `json:"content"     description:"内容"`
	CommunityId int64       `json:"communityId" description:"所属社区"`
	AuthorId    int64       `json:"authorId"    description:"作者用户id"`
	CreateTime  *gtime.Time `json:"createTime"  description:""`
	UpdateTime  *gtime.Time `json:"updateTime"  description:""`
}
