// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         uint64      `json:"id"         description:""`
	UserId     int64       `json:"userId"     description:""`
	Username   string      `json:"username"   description:""`
	Password   string      `json:"password"   description:""`
	Email      string      `json:"email"      description:""`
	Gender     int         `json:"gender"     description:""`
	CreateTime *gtime.Time `json:"createTime" description:""`
	UpdateTime *gtime.Time `json:"updateTime" description:""`
}
